### ISSUE TITLE
testdevice

### ISSUE THREAD

**Issue by aldwnesx** [sagarshende23/flutter_admob#1]
Hi, many thanks for your tut video!

What is "testdevice" for? I replace the unitid with my own admod now I'm getting errors

```
 A resource failed to call release.
W/flutter (26998): onRewardedVideoAdFailedToLoad: 3
I/Ads     (26998): Ad failed to load : 3
```

**Comment by sagarshende23** [comment]
Sorry for the late reply,

Testdevice Id is Not Necessary, You can Remove it
